# Generated by Django 3.2 on 2021-05-18 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('password', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('description', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('project_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TAApp.administrator')),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('password', models.CharField(max_length=20, null=True)),
                ('role', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('project_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TAApp.instructor')),
            ],
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('description', models.CharField(max_length=50, null=True)),
                ('labForCourse', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='TAApp.course')),
                ('labTA', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='TAApp.ta')),
                ('project_manager', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='TAApp.instructor')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='TAApp.instructor'),
        ),
        migrations.AddField(
            model_name='course',
            name='instructorTA',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='TAApp.ta'),
        ),
        migrations.AddField(
            model_name='course',
            name='project_manager',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='TAApp.administrator'),
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('description', models.CharField(max_length=50, null=True)),
                ('instructorTA', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='TAApp.ta')),
            ],
        ),
    ]
