# Generated by Django 3.2 on 2021-04-28 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TAApp', '0002_myuser_role'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='Courses',
        ),
    ]
